---
- git: 'https://github.com/bdellegrazie/ansible-role-prometheus_exporter.git'
  version: 'v2.0.3'
  dst: $MOLECULE_EPHEMERAL_DIRECTORY/roles/bdellegrazie.ansible-role-prometheus_exporter/
- git: 'https://github.com/geerlingguy/ansible-role-postgresql.git'
  version: '3.0.0'
  dst: $MOLECULE_EPHEMERAL_DIRECTORY/roles/geerlingguy.postgresql/
